exclude: parse_emails/tests/test_data/.*|.circleci/config.yml|parse_emails/__init__.py
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-docstring-first
          - id: check-json
            exclude: .vscode/.*
          - id: check-yaml
          - id: debug-statements
            language_version: python3
          - id: name-tests-test
    - repo: https://github.com/hadialqattan/pycln
      rev: v2.5.0
      hooks:
        - id: pycln
    - repo: https://github.com/pycqa/flake8
      rev: "6.0.0"
      hooks:
          - id: flake8
    - repo: https://github.com/pre-commit/mirrors-autopep8
      rev: v2.0.1
      hooks:
          - id: autopep8
    - repo: https://github.com/PyCQA/isort
      rev: "5.12.0"
      hooks:
          - id: isort
            types: [python]
    - repo: https://github.com/asottile/pyupgrade
      rev: v3.3.1
      hooks:
          - id: pyupgrade
            args: [--py38-plus]
    - repo: https://gitlab.com/smop/pre-commit-hooks
      rev: v1.0.0
      hooks:
          - id: check-poetry
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.991
      hooks:
        -   id: mypy
            additional_dependencies: [
                types-PyYAML==5.4.3,
                types-setuptools==57.0.0,
                types-ujson==0.1.1,
                types-pytz==2021.1.0,
                types-requests==2.25,
                types-decorator==0.1.5,
                types-dateparser==0.1.3,
                types-tabulate==0.1.1,
                types-python-dateutil==0.1.4
                ]
